export const AnalysisStatus = {
  OK: "ok",
  WARN: "warn",
  ERROR: "error"
};

export const Anomaly = {
  RELATIONAL_TONE: "RELATIONAL_TONE",
  ADVICE_FOUND: "ADVICE_FOUND",
  INVITATION_FOUND: "INVITATION_FOUND",
  EMPATHY_FOUND: "EMPATHY_FOUND",
  QUESTION_FOUND: "QUESTION_FOUND",
  OVERLONG_RESPONSE: "OVERLONG_RESPONSE"
};
